language: python

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=py36-django-22
    - python: 3.7
      env: TOX_ENV=py37-django-32
    - python: 3.8
      env: TOX_ENV=py38-django-32
    - python: 3.9
      env: TOX_ENV=py39-django-32
    - python: 3.8
      env: TOX_ENV=py38-django-master
    - python: 3.9
      env: TOX_ENV=py39-django-master
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py38-django-master
    - env: TOX_ENV=py39-django-master

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: pip install pytest-django

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

install:
  - pip install -r requirements/travis.txt

after_success:
  - codecov -e TOX_ENV
