language: python

python:
  - "3.5"

env:
  - TOX_ENV=py35-django-18
  - TOX_ENV=py34-django-18
  - TOX_ENV=py33-django-18
  - TOX_ENV=py27-django-18
  - TOX_ENV=py35-django-19
  - TOX_ENV=py34-django-19
  - TOX_ENV=py27-django-19
  - TOX_ENV=py35-django-110
  - TOX_ENV=py34-django-110
  - TOX_ENV=py27-django-110
  - TOX_ENV=py36-django-111
  - TOX_ENV=py35-django-111
  - TOX_ENV=py34-django-111
  - TOX_ENV=py27-django-111
  - TOX_ENV=py36-django-master
  - TOX_ENV=py35-django-master

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py35-django-master
    - env: TOX_ENV=py36-django-master

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: pip install pytest-django

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

install:
  - pip install -r requirements/travis.txt

after_success:
  - codecov -e TOX_ENV
